#### Add all the constant values here

class GAME():
	CANVAS_WIDTH = 800
	CANVAS_HEIGHT = 600
	REMAINING_SECONDS = 60 ## 1 minute 
	SCORE_DIALOG_POS_X = 1200
	SCORE_DIALOG_POS_Y = 120
	SCORE_DIALOG_WIDTH = 200
	SCORE_DIALOG_HEIGHT= 100
	SCORE_VALUE_POS_X =  15
	SCORE_VALUE_POS_Y = 30

	POLYGONS_TO_GENERATE = 20
	REGION_X = 50
	REGION_Y = 50

	TEXT_FONT_SIZE = 15

